import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css"
import Todo from '../components/Todo'
import TodoItem from '../components/TodoItem';
import Card from '../components/Card';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextApp</title>
        <meta
        name="description"
        content='Generated by SK'
        />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Todo/>
    </div>
  );
}